## Arrays

### Creating Arrays

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
myarray

array([1, 2, 3, 4, 5])

In [4]:
mylist2 = [21,233,45,67,56]

In [5]:
mylists = [mylist, mylist2]
print(mylists)

[[1, 2, 3, 4, 5], [21, 233, 45, 67, 56]]


In [6]:
## if you want to create a proper n dimensional array out of a list of lists then make sure both the lists have the same
## number of elements in it
myarray2 = np.array(mylists)
print(myarray2)

[[  1   2   3   4   5]
 [ 21 233  45  67  56]]


In [7]:
#shape of array
print(myarray2.shape)

(2, 5)


In [8]:
#type of array 
myarray2.dtype

dtype('int32')

In [9]:
#### special type of arrays

## array of zeros 
d1_zeros = np.zeros(5)
print("Matrix of zeros:",d1_zeros)
print("Data type of matrix (applicable to all special mupy arrays created here):",d1_zeros.dtype)

## array of ones
d2_ones = np.ones(4)
d3_ones = np.ones([3,6])
print("Matrix of ones:",d2_ones)
print("Matrix of ones:",d3_ones)

## identity matrix 
identity = np.eye(3)
identity1 = np.eye(1,2)
print("Identity matrix 1:", identity)
print("Identity matrix 2:",identity1)

## empty matrix OR basically array of zeros
empty = np.empty([2,3])
print("Empty matrix", empty)

Matrix of zeros: [0. 0. 0. 0. 0.]
Data type of matrix (applicable to all special mupy arrays created here): float64
Matrix of ones: [1. 1. 1. 1.]
Matrix of ones: [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Identity matrix 1: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity matrix 2: [[1. 0.]]
Empty matrix [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
## matrix with number range

range1 = np.arange(1, 20 , 2)
print("Range of numbers matrix 1:", range1)


range2 = np.arange(10)
print("Range of numbers matrix 2:", range2)

Range of numbers matrix 1: [ 1  3  5  7  9 11 13 15 17 19]
Range of numbers matrix 2: [0 1 2 3 4 5 6 7 8 9]


### Using arrays and scalars

In [11]:
5/2

2.5

In [12]:
array3 = np.array([1,2,3,4,5])

In [13]:
# duplicate contents x number of times
print("Multiplication by 3 ", array3 * 3)

# element wise multiplication 
print("Squared array ", array3 ** 2)

# array subtraction
print("Subtraction of array by itself ", array3 - array3)

array3 = np.array([1,2,3,4,5])
#Array division
print("Element wise inversion of elements ", 1/array3)

Multiplication by 3  [ 3  6  9 12 15]
Squared array  [ 1  4  9 16 25]
Subtraction of array by itself  [0 0 0 0 0]
Element wise inversion of elements  [1.         0.5        0.33333333 0.25       0.2       ]


### Indexing and slicing arrays

In [14]:
iandsarray = np.arange(1,11)
print("Array:", iandsarray)
print("6th element of array",iandsarray[5])
print("Array slice:", iandsarray[0:5])

#make a copy of the array
arrcopy = iandsarray.copy()
print("Copied array:", arrcopy)

arrcopy[0:5] = 99
print("Array with replaced elements:", arrcopy)


Array: [ 1  2  3  4  5  6  7  8  9 10]
6th element of array 6
Array slice: [1 2 3 4 5]
Copied array: [ 1  2  3  4  5  6  7  8  9 10]
Array with replaced elements: [99 99 99 99 99  6  7  8  9 10]


### Indexing and slicing 2d arrays

In [15]:
arr2d = np.array(([1,2,3,4], [5,6,7,8], [9,10,11,12]))
print("2d array:", arr2d)

2d array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print("2D array row:", arr2d[1])
print("2D array single element:", arr2d[1][2])
print("2d array slicing:", arr2d[:2,1:])

2D array row: [5 6 7 8]
2D array single element: 7
2d array slicing: [[2 3 4]
 [6 7 8]]


### Fancy Indexing

In [17]:
fancy = np.ones((5,5))

#get the number of rows 
nrows = fancy.shape[1]

#row wise element assignment 
for i in range(nrows):
    fancy[i] = i

print(fancy)
print("Fancy indexing: fancy[[2,4]]:", fancy[[2,4]])
print("Fancy indexing: fancy[[4,2]]:", fancy[[4,2]])

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
Fancy indexing: fancy[[2,4]]: [[2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4.]]
Fancy indexing: fancy[[4,2]]: [[4. 4. 4. 4. 4.]
 [2. 2. 2. 2. 2.]]


In [18]:
shapy = np.arange(50).reshape(10,5)
shapy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [19]:
#Transpose matrix 
shapy.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [20]:
#dot product 
np.dot(shapy.T,shapy)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [21]:
# 3D array creation
arr_3D = shapy.reshape((2,5,5))
arr_3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [22]:
arr3D_transpose = arr_3D.transpose((1,0,2))
arr3D_transpose

array([[[ 0,  1,  2,  3,  4],
        [25, 26, 27, 28, 29]],

       [[ 5,  6,  7,  8,  9],
        [30, 31, 32, 33, 34]],

       [[10, 11, 12, 13, 14],
        [35, 36, 37, 38, 39]],

       [[15, 16, 17, 18, 19],
        [40, 41, 42, 43, 44]],

       [[20, 21, 22, 23, 24],
        [45, 46, 47, 48, 49]]])

In [23]:
#swap axes 
swapy = np.array([[1,2,3],[4,5,6]])
print(swapy)
swapy.swapaxes(0,1)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### Universal array functions

In [24]:
#square root 
A = np.sqrt(np.arange(1,11))
A

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [25]:
#exponential function
B = np.exp(np.arange(1,11))
B

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [26]:
#Add two arrays
sum_of = np.add(A,B)
sum_of

array([3.71828183e+00, 8.80326966e+00, 2.18175877e+01, 5.65981500e+01,
       1.50649227e+02, 4.05878283e+02, 1.09927891e+03, 2.98378641e+03,
       8.10608393e+03, 2.20296281e+04])

In [27]:
# create a random array of n number from a normal distribution
np.random.randn(10)

array([ 0.87389662, -0.06915625,  0.7330384 , -0.98996477, -1.03165948,
        0.47206341,  1.27779911,  1.35324284,  1.64972426,  0.85873817])

### Array Processing

In [29]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([100,200,300,400])
bool_arr = np.array([True,True, False, False])
#Use a function to extract values you want - if condition true then choose value from first array else from 2nd array
choose_nos = np.where(bool_arr, arr1, arr2)
print(choose_nos)

#use np.where to clean up arrays
from numpy.random import randn
random_arr = randn(5,5)
clean_rand = np.where(0<random_arr,0,random_arr)
print(clean_rand)

[  1   2 300 400]
[[ 0.         -1.25230062  0.          0.         -0.51086507]
 [-0.7646859  -1.77978813  0.         -0.41925339  0.        ]
 [ 0.          0.          0.         -0.26792647 -0.28251846]
 [-0.06202134  0.          0.         -0.54439698  0.        ]
 [ 0.         -0.28051201  0.          0.          0.        ]]


In [38]:
#Sum elements in an array
range_arr = np.arange(1,26).reshape(5,5)
print(range_arr)

sum_of_all = np.sum(range_arr)
print(sum_of_all)

sum_along_row = np.sum(range_arr,1)
print(sum_along_row)

sum_along_col = np.sum(range_arr,0)
print(sum_along_col)

mean_of_arr = np.mean(range_arr)
print(mean_of_arr)

std_of_arr = np.std(range_arr)
print(std_of_arr)

var_of_arr = np.var(range_arr)
print(var_of_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
325
[ 15  40  65  90 115]
[55 60 65 70 75]
13.0
7.211102550927978
52.0


In [44]:
#return true if any in the arr is true
print(bool_arr.any())
print(bool_arr.all())

True
False


In [47]:
##array sort
sort_arr = randn(5)
print(sort_arr)
sort_arr.sort()
print("After sorting ",sort_arr)

[ 2.07545177 -0.51694903  0.2447257  -0.26102595 -0.37066379]
After sorting  [-0.51694903 -0.37066379 -0.26102595  0.2447257   2.07545177]


In [50]:
# find out unique values 
dup_arr = np.array([1,2,3,5,2,3,1])
print("Array with duplicate values ",dup_arr)
print("Array with unique values ", np.unique(dup_arr))

Array with duplicate values  [1 2 3 5 2 3 1]
Array with unique values  [1 2 3 5]


In [49]:
#Test values in 1d array
np.in1d([1,3,6],dup_arr)

array([ True,  True, False])